// Planes de servicio del brief (sección 5). La migración 0004 los crea para los
// estudios que ya existían y el seed para los nuevos; después se editan en la base.

export const SERVICE_PLANS = [
  {
    key: "negocio_en_orden",
    name: "Negocio en Orden",
    description: "Para pequeñas empresas que necesitan centralizar y ordenar su operación mensual.",
    max_legal_entities: 1,
    max_users: 5,
    max_modules: 1,
    position: 1,
    features: [
      "Responsable del estudio asignado",
      "Calendario de obligaciones",
      "Vencimientos, importes y enlaces de pago",
      "Repositorio seguro de documentos",
      "Carga y clasificación asistida",
      "Solicitudes con seguimiento",
      "Alertas automáticas",
      "Resumen operativo mensual",
      "Primera respuesta en menos de 24 horas hábiles",
      "Revisión trimestral",
    ],
  },
  {
    key: "empresa_en_control",
    name: "Empresa en Control",
    description: "Para PyMEs con más movimiento, empleados o varias personas involucradas en la administración.",
    max_legal_entities: 2,
    max_users: 12,
    max_modules: 3,
    position: 2,
    features: [
      "Todo lo de Negocio en Orden",
      "Roles y permisos por área",
      "Tablero mensual de situación",
      "Reunión mensual",
      "Seguimiento de documentación pendiente",
      "Automatizaciones y recordatorios configurables",
      "Indicadores operativos básicos",
      "Atención prioritaria",
    ],
  },
  {
    key: "gestion_estrategica",
    name: "Gestión Estratégica",
    description: "Para organizaciones de mayor complejidad que necesitan información para decidir.",
    max_legal_entities: 5,
    max_users: 25,
    max_modules: 5,
    position: 3,
    features: [
      "Todo lo de Empresa en Control",
      "Equipo de atención asignado",
      "Informe mensual ejecutivo",
      "Reunión mensual de dirección",
      "Planificación fiscal y financiera",
      "Proyecciones y alertas de desvíos",
      "Indicadores personalizados",
      "Automatizaciones avanzadas",
      "Seguimiento quincenal de temas críticos",
    ],
  },
] as const;
